project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
    - text: Hands on Exercises
      menu:
        - text: Geospatial Data Wrangling with R [1]
          href: Hands-On_Ex/Hands-On_Ex1/Hands-On_Ex1A.qmd
        - text: Choropleth Mapping with R [2]
          href: Hands-On_Ex/Hands-On_Ex1/Hands-On_Ex1B.qmd
        - text: Spatial Weights and Applications [3]
          href: In-Class_Ex/In-Class_Ex1.qmd
        - text: Global and Local Measures of Spatial Autocorrelation [4]
          href: Hands-On_Ex/Hands-On_Ex2/Hands-On_Ex2.qmd
        - text: Geographical Segmentation with Spatially Constrained Clustering Techniques [5]
          href: Hands-On_Ex/Hands-On_Ex3/Hands-On_Ex3.qmd
          
          
    - text: Take Home Exercises
      menu:
        - text: Take Home Exercise1
          href: Take-Home_Ex/Take-Home_Ex1.qmd
        - text: Take Home Exercise2
          href: Take-Home_Ex/Take-Home_Ex2.qmd
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

