project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
    - text: Hands on Exercises
      menu:
        - text: Hands On Exercise 1A
          href: Hands-On_Ex/Hands-On_Ex1/Hands-On_Ex1A.qmd
        - text: Hands On Exercise 1B
          href: Hands-On_Ex/Hands-On_Ex1/Hands-On_Ex1B.qmd

    - text: In Class Exercises
      menu:
        - text: In Class Exercise 1
          href: In-Class_Ex/In-Class_Ex1.qmd

    - text: Take Home Exercises
      menu:
        - text: Take Home Exercise1
          href: Take-Home_Ex/Take-Home_Ex1.qmd
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

